### ISSUE TITLE
calc_inertia.py calculates inertia for shells 

### ISSUE THREAD

**Issue by Paschwuerfler** [gstavrinos/calc-inertia#7]
I find it very frustrating that this fact is not clearly stated in the readme. 

Why i think this is the case: 

I used blender to generate a sphere and checked my results against standard formulas 
( I_sphere = 0.4 * m * r^2; I_sphericalshell = 0.666 * m * r^2) 

My results match very closely to theoretical spherical shells.

**Comment by gstavrinos** [comment]
Hey, thanks for reaching out. Sorry if I frustrated you. That's definitely not my purpose with my open source projects! :)

Regarding the problem you are facing, I think that I use formulas for solid bodies in all of my calculations, but I could be wrong.

If you are using an stl or dae (any model file exported from Blender) and not a primitive shape to calculate your inertia matrix, please keep in mind that the bounding box is used instead.

If this is your case, you could try calculating the inertia for the bounding box of your sphere, and check if this is the matrix you are getting from my script.

On that note though, I think I should include a flag that makes collision tags the preferred inertia calculation input, thus allowing for complicated visual shapes (or simple modeled ones) and simpler collision/inertia calculations.

The above suggestion introduces a small problem though: What if you sometimes need the visual tag for inertia calculation and some others the collision one?

I would love to hear your input on that one, and of course, the results for my suggested test.

**Comment by gstavrinos** [comment]
Hey @Paschwuerfler, any update on this?
